id: AIT117
title: Human Basal Ganglia taxonomy
description: Atlas of Human basal ganglia, developed in collaboration with the BRAIN Initiative Cell Census Network (BICCN).
matrix_file_id: CellXGene_dataset:HMBA_Human_BG_082024_AIT_to_CAP
github_org: Cellular-Semantics
repo: nhp_basal_ganglia_human_taxonomy
author: https://orcid.org/0000-0002-4436-969X
accession_id_prefix: AIT117
citation: ''
creators:
  - https://orcid.org/0000-0002-4436-969X